version: '3.1'
services:
  books-backend:
    build: ./
    image: halosan/books-backend:latest
    links:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGO_CONN: "mongodb://root:password@mongo:27017"
    container_name: books-backend

  mongo:
    image: mongo:3.2-jessie
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - books-backend-mongo:/data/db
    container_name: books-backend-mongo

  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    links:
      - mongo
    container_name: books-backend-mongo-express

volumes:
  books-backend-mongo:
    external: true
